### ISSUE TITLE
Default wallpaper images need resizing or remaking?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-images#9]
At least one of our wallpaper images has been reported to show banding on some displays: https://github.com/BunsenLabs/bunsen-configs/pull/75#issue-172743654

This might be because they are too small for modern display sizes, or because they need to be recreated with full 32 bit colour/monochrome range.

**Comment by johnraff** [comment]
@tknomanzr and @Head-on-a-Stick what size displays were you seeing banding on? Our wallpapers are currently 2880px × 1800px but at 180~480 kB they're not so big, suggesting they might have been fiercely compressed?

**Comment by tknomanzr** [comment]
I don't see it at all on 1920x1080 monitors. The gradients are nice and soft at that resolution. At 2560 x 1600, there is some noticeable banding. The resolution is not the problem. It is going to be the pixels per inch (ppi). Open Gimp, create a new image, and notice Under Advanced Options, the settings for x and y resolutions. I would see how the images look with x and y at 144. Check the size of a .png at that pixel density. If it is too large, edge down to 120 or so, bottom end at 100. 
This is the actual pixel density of the wallpaper:

> 96.012 × 96.012 ppi

That is straight from BL-beam in wallpapers, loaded into gimp. With the original gimp files, we can re-export the .pngs with a higher pixel density. Try to balance file size with image quality, basically. 

I am seeing banding because I am viewing the picture at a pixel density at ~200 ppi. The banding doesn't actually exist. It is my display making stuff up because there is missing information for a display running at 200 ppi. On a lossless .png you can probably safely up the compression considerably as well.

**Comment by johnraff** [comment]
> The resolution is not the problem. It is going to be the pixels per inch (ppi).

Sorry, I don't get this. I thought ppi was just a bit of meta-data that had significance only for printers that were going to put the image on a physical piece of paper. Surely a pixel is a pixel, and the issue is arising because there are more pixels on the screen than there are in the image? If you raised the dpi on an image of a certain pixel size, wouldn't that just instruct the printer (or display?) to display it at a smaller size? Or am I missing something about how images are rendered on a display?

My display is 1440x900 so I can't check any of this - everything looks fine.

Unfortunately I have no idea where the original gimp files are, or who had them. @hhhorb or @capn-damo ?

Can you try increasing the size of a wallpaper image in gimp - using the best algorithm - and seeing if the banding is then gone? (Maybe gimp has more powerful image resizing tools than an LCD display does if forced to expand an image on the fly?) 

I have just tried scaling up the images (using the "cubic" algorithm), and while I can't use the result as a wallpaper on my smaller screen, I can inspect it full-size in gimp, using the scrollbars. Yes, the grey images especially show some banding. In fact I can see it even in the original grey versions, but not in the green ones, so part of the problem might have arisen when the green images were decoloured.

I'm off to deviantart to see if I can track down the original image - maybe it's bigger.
EDIT: https://rashadisrazzi.deviantart.com/art/Beam-531144169
No, the largest is the same at 2880x1800.

@hhhorb 's remakes here: https://github.com/hhhorb/bunsen-wallpapers
But @capn-damo subsequently reprocessed them, moving the logo in a bit.

**Comment by ben2s** [comment]
> I thought ppi was just a bit of meta-data that had significance only for printers that were going to put the image on a physical piece of paper.

This is correct (developer in a company creating prepress software here).  When displaying on a computer monitor, the ppi (pixels per inc) or dpi (dots per inch) is not used, unless you're asking for a preview of the printed size (and this is always an approximation).

> Surely [...] the issue is arising because there are more pixels on the screen than there are in the image?

Probably.  Note however that banding is somewhat complex, and may occur even if there are **more** pixels in the image than can be shown on the display.  This depends on how it is scaled down, what the colour settings of the OS and display are, and even on the colour perception of whoever is looking at the image.

The easiest way to suppress banding is to add noise to a gradient, but this has to be done carefully to avoid making the image look grainy (unless that's a look you want of course).

**Comment by tknomanzr** [comment]
Using proprietary tools, I am able to reduce the banding by upping the color depth to 16-bit color and adding a bit of noise to it. This comes at significant cost to file size up to about 8.6 megs. A little research shows that Gimp needs to be at least version 2.9.2 to use 16-bit rgb channels. I can confirm the original image was 8-bit rgb. 
https://image.ibb.co/jfrba7/BL_beam2.png

**Comment by johnraff** [comment]
Yup, all the banding seems to be gone, as far as I can see it anyway.
But, that's a *huge* increase in file size - the original is 489 kB.
There's no way to get it down somewhere under 2MB I suppose?

**Comment by johnraff** [comment]
I tried exporting your debanded image as a .jpg. It came down to 577 kB. I guess jpgs are inherently fuzzier.
Is this usable at all?
https://drive.google.com/file/d/1mCxXdggCS4pkYc3_rZjfmqO9qH9WsoOm/view?usp=sharing

**Comment by tknomanzr** [comment]
I actually thought about exporting it as a jpeg. Jpegs are lossy compression but far more efficient than pngs. We don't really need the transparency information that png's offer. I'd stick with the jpeg and I'll stash the png's back someplace. I think I am a member of the Bunsenlabs Deviant Art group so possibly I could post them there. We'll have to fix up the rest of them, and in the interests of FOSS purism, I guess I should follow the instructions on the forums to get a newer version of Gimp running.

**Comment by ben2s** [comment]
> I tried exporting your debanded image as a .jpg. It came down to 577 kB. I guess jpgs are inherently fuzzier.
Is this usable at all?
https://drive.google.com/file/d/1mCxXdggCS4pkYc3_rZjfmqO9qH9WsoOm/view?usp=sharing

I'm not usually a fan of jpeg because of the possibility of artifacts (you can see some if you really zoom in on the logo), but that looks very good indeed.  If it counts for anything, my vote goes to the jpeg compression (at least for this case).

Note that jpeg artifacts get progressively worse, so any future editing should definitely be done on the png files.

**Comment by tknomanzr** [comment]
I exported all 4 of the images in question to jpegs at ~.5 mb each. Here they are:
[![BL-beam.th.jpg](https://cdn.scrot.moe/images/2018/03/10/BL-beam.th.jpg)](https://scrot.moe/image/6QXXq)
[![BL-beam-grey.th.jpg](https://cdn.scrot.moe/images/2018/03/10/BL-beam-grey.th.jpg)](https://scrot.moe/image/6QcBy)
[![BL-beam-plain.th.jpg](https://cdn.scrot.moe/images/2018/03/10/BL-beam-plain.th.jpg)](https://scrot.moe/image/6QmfU)
[![BL-beam-plain-grey.th.jpg](https://cdn.scrot.moe/images/2018/03/10/BL-beam-plain-grey.th.jpg)](https://scrot.moe/image/6QDzm)
I still see a small amount of banding in the lower right corner but it is much better than it was. I don't think I can add much more noise without it becoming very noticeable.
Exported images are hosted on [scrot.moe](https://scrot.moe/tknomanzr), while the originals are stashed in my file server for the time being.

**Comment by Head-on-a-Stick** [comment]
> I am able to reduce the banding by upping the color depth to 16-bit color

Is it possible to use 24-bit (*full colour*) or perhaps even 32-bit (*deep colour*) instead?

The more colours available, the more gradual the gradient can be.

**Comment by johnraff** [comment]
> I am able to reduce the banding by upping the color depth to 16-bit color
> 
> Is it possible to use 24-bit (full colour) or perhaps even 32-bit (deep colour) instead?

Did you notice the huge increase in file size that came with going from 8-bit to 16-bit? Is it possible to go to 24 or 32 bits while keeping the wallpaper file size to something sane?

How do you find the jpg files that @tknomanzr posted? Is the banding there still unnacceptable on your display?

**Comment by Head-on-a-Stick** [comment]
> from 8-bit

The original image only has 256 colours?

I had no idea the colour depth was so restricted, I would never have supported using that image had I known that.

In my opinion, 24-bit is the bare minimum (~16 million colours) with 32-bit being preferred.

I can still see banding (and dithering) on the new high-resolution images, even when scaled to my 1280x800 display.

**Comment by johnraff** [comment]
> I had no idea the colour depth was so restricted, I would never have supported using that image had I known that.

I don't think these wallpaper images have been kept secret. Discussions with examples go way back to last year on the BL forums.

Anyway, If you'd care to go back to the original Deviantart images, or @hhhorb 's repo, and redo them, I'll be happy to put improved versions in the package. (As long as they're not 10MB each.) I've said on numerous occasions that I'm not a graphics expert and I've no intention of becoming one.

@tknomanzr 's images look fine to me (and @ben2s) ...

**Comment by Head-on-a-Stick** [comment]
> Discussions with examples go way back to last year on the BL forums.

Yes, I know, I dropped the ball completely there, sorry!

> If you'd care to go back to the original Deviantart images

I'll give it a go tonight, how large can we go on the images?

**Comment by johnraff** [comment]
I'd say under 2MB, but @tknomanzr what do you think?

**Comment by Head-on-a-Stick** [comment]
OK, bad news: just downloaded the source material:
```
alpine:~/Downloads$ file *.png
1920-x-1080.png: PNG image data, 1920 x 1080, 8-bit/color RGB, non-interlaced
1920-x-1200.png: PNG image data, 1920 x 1200, 8-bit/color RGB, non-interlaced
2560-x-1440.png: PNG image data, 2560 x 1440, 8-bit/color RGB, non-interlaced
2880-x-1800.png: PNG image data, 2880 x 1800, 8-bit/color RGB, non-interlaced
Preview.png:     PNG image data, 2560 x 1440, 8-bit/color RGB, non-interlaced
alpine:~/Downloads$
```
8 bits per colour, RGB only (no alpha) means that they have 24 bits of colour depth already.

The problem lies in the gradient algorithm chosen by the artist or perhaps that's just as good as it gets for such an effect, I really don't know.

The banding is still visible on the original images and I can only apologise to the Team for missing this fault earlier, I prefer to keep my backlight as low as possible and the problem only becomes apparent at higher brightness levels.

I can try to recreate the image with a better gradient effect but I don't hold out much hope.

**Comment by hhhorb** [comment]
Is this a show stopper? If someone has a hi-res monitor, we could either provide a different branded image that matches the default gtk theme in an extras package or just leave it to the user to create their own branded image or use an unbranded one.

I'm wondering how many people out of those with large screens are even bothered by banding.

What's the color depth of the default stretch wallpapers?

**Comment by Head-on-a-Stick** [comment]
> Is this a show stopper?

No, I don't think so.

As I said it is only really apparent at high brightness levels and perhaps *all* gradients look like that in such circumstances.

**Comment by hhhorb** [comment]
In that case, I recommend we include Bill's remakes in an extras package and leave this issue open for the time being to catch any complaints.

**Comment by Head-on-a-Stick** [comment]
Bill's images are an improvement but the cost in respect of file size is prohibitive (IMO).

If we are to accept the minor banding (which is only visible in certain circumstances) then we should probably just stick to the originals.

**Comment by johnraff** [comment]
> Bill's images are an improvement but the cost in respect of file size is prohibitive

What images do you mean? The jpgs he posted [here](https://github.com/BunsenLabs/bunsen-images/issues/9#issuecomment-372072289) are only 6~700 kB. They still seem to be better than the original pngs, for a ~20% size increase.

**Comment by Head-on-a-Stick** [comment]
> only 6~700 kB.

Ooops, sorry, I thought they were larger than that.

I agree that we should use Bill's images then, they are an improvement.

**Comment by johnraff** [comment]
OK for now I'll put Bill's jpg remakes into bunsen-images, and we'll see how it goes from there.

**Comment by johnraff** [comment]
^Doing this now. Unfortunately the .jpg ending means that the filenames will change. Till the official release, at least, I'll just *add* the jpg's so that existing users won't see their wallpaper mysteriously disappear. Change the paths in **bunsen-configs**, and maybe later the extraeneous files can be removed.

EDIT: done.

**Comment by johnraff** [comment]
My apologies here. I forgot to link to the *adjusted* wallpapers, with the logo moved further toward the centre. This is necessary for the BL-beam and BL-beam-grey versions, because otherwise on an older "square" display the logo is halfway off the screen and doesn't look good at all.

Here is Damo's adjusted image (ver. 2 of the two he posted [here](https://forums.bunsenlabs.org/viewtopic.php?pid=59598#p59598)): https://scrot.moe/image/62Vxy
and the discussion starts here: https://forums.bunsenlabs.org/viewtopic.php?pid=59587#p59587

Unfortunately he didn't post a greyscale version, so the grey one we formerly had was something I had hacked up on Gimp. That might explain the bad banding @Head-on-a-Stick had originally complained of.

@tknomanzr if you could possibly redo whatever you did before to improve the pngs then make jpgs it would help get this show on the road. This time only two images will be needed, just the ones with logos. Damo's green png > fix colour depth > make jpg, and if you could do a greyscale conversion for the grey version?

 Sorry to add to your workload.

**Comment by tknomanzr** [comment]
Let's see how these two work. Because we have text layered over a gradient, I had to redo the layering before I add the noise.  Fortunately, we have the pieces required to rebuild the image, otherwise I would not be able to guarantee you any kind of results. 
[![BL-beam.th.jpg](https://cdn.scrot.moe/images/2018/03/24/BL-beam.th.jpg)](https://scrot.moe/image/6b4KL)
[![BL-beam-grey.th.jpg](https://cdn.scrot.moe/images/2018/03/24/BL-beam-grey.th.jpg)](https://scrot.moe/image/6b8ib)

****NOTE:** I am putting a note here to remind myself to start a conversation after Helium releases regarding whether and how we should store originals for Official Bunsenlabs images. If we were able to do so, it would certainly help with re-duplication of effort when the unexpected happens.

**Comment by johnraff** [comment]
Many thanks! I'll put those in **bunsen-images** and push it out today.

+1 about organizing our resources so those who follow on can pick up.

**Comment by johnraff** [comment]
I've committed those two images to GitHub, but just noticed a small issue: the logos are now bigger. Check the previous .png files, eg https://github.com/BunsenLabs/bunsen-images/blob/helium-dev/bl-img/wallpapers/default/BL-beam.png

If it's difficult, leave it, but I think the smaller logos look more elegant, if it's possible to do that.

**Comment by tknomanzr** [comment]
Ahh yes, one of the benefits of storing our art assets as actual Gimp files is that anyone with the time, knowledge, and inclination could then make small changes such as these. However, since, I have the originals at present, I am glad to make the changes. The question is whether Github is the place to store them. On the one hand, it would give us versioning, branches, etc but these original files tend to be quite large.

**Comment by tknomanzr** [comment]
See how these two work:
[![BL-beam.th.jpg](https://cdn.scrot.moe/images/2018/03/25/BL-beam.th.jpg)](https://scrot.moe/image/6bhfy)
[![BL-beam-grey.th.jpg](https://cdn.scrot.moe/images/2018/03/25/BL-beam-grey.th.jpg)](https://scrot.moe/image/6f0KU)

**Comment by ghost** [comment]
I'm a bit late to the show, but @tknomanzr's latest batch of images shows very noticable JPEG artifacts on my fancy new monitor (24", 1920x1200, not HiDPI), especially the coloured one. where the light beam blends into the upper-left's green-then-turquoise. I wouldn't ship them like this.

**Comment by hhhorb** [comment]
^ Do any of the wallpapers look good on your monitor?

**Comment by tknomanzr** [comment]
^ I may need to reduce the noise somewhat and re-export them with much less compression. I think they are sitting at around 75%. The file sizes keep growing on me, so I upped the compression some.

I think I may have killed the backlinks on some of those earlier images because my scrot.moe account was a huge mess and I was trying to organize it somewhat. 

It's weird to think that I used to exploit the limitations of raster graphics to create "art" and now I am banging my head up against one such limitation. At any rate, I will mess with it some more in the morning when my eyes aren't so tired and see if I can improve things any.

**Comment by ben2s** [comment]
I see quite a bit of noise - notably more than in the previous batch, especially in the lower right corner - but no JPEG artifacts.  When comparing https://scrot.moe/image/6QXXq to https://scrot.moe/image/6bhfy I feel the top left corner is better in the latest (less banding), but the bottom right was better before (less noise).
Anyway, at some point we will have to accept that it will never be perfect for everyone.  There are just too many variables.

**Comment by johnraff** [comment]
OK for now I'll put the latest jpgs in **bunsen-images**, change filepaths in **bunsen-configs** to match, and start building a beta iso. We can see if we get any feedback from our user base. The previous pngs will remain too, at least for a while.

EDIT: Extremely sorry, but these are still different from the originals. Please see below.

**Comment by johnraff** [comment]
@tknomanzr Please forgive me if you think I'm being too picky here, but these latest jpgs are still subtly different from the original pngs in their styling and layout. 
The logos are further away from the beam, very slightly larger, and the flame is differently placed. The originals by @capn-damo are very nice IMO, and if possible I think we should try to preserve that design.

Compare, the new design:
[![BL-beam.th.jpg](https://cdn.scrot.moe/images/2018/03/25/BL-beam.th.jpg)](https://scrot.moe/image/6bhfy)
and Damo's original:
[![BL-beam.th.png](https://cdn.scrot.moe/images/2018/03/29/BL-beam.th.png)](https://scrot.moe/image/6fdcl)

(My eyes are quite inadequate to say anything about banding and artifacts.)

**Comment by tknomanzr** [comment]
Unfortunately, I am not able to find the original Bunsenlabs .svg that @damo used. So here is what I did: I loaded the flame image that I used with the flame over the "e" and moved it slightly to the right, then colorized it with the color from the original image, using Inkscape. 

I then brought the image into Gimp 2.9.2, and positioned and scaled it using @damo's original wallpaper as a guide. I then removed the original wallpaper. Then, I add a slight bit of noise to the image (I tried to be a bit more subtle here.). The grey version needed a bit more noise even than the color version in order to reduce the banding. 

However, it should be noted that there is the slightest bit of difference between the kerning of the fonts that @damo used than the version of the bl-flame-text.svg that sits in our Github repository, so it is not a pixel-perfect match. It is very close. however. 

[![BL-beam-1.th.png](https://cdn.scrot.moe/images/2018/03/29/BL-beam-1.th.png)](https://scrot.moe/image/91iwy)
[![BL-beam-plain-1.th.png](https://cdn.scrot.moe/images/2018/03/29/BL-beam-plain-1.th.png)](https://scrot.moe/image/91nOU)
[![BL-beam-grey-1.th.png](https://cdn.scrot.moe/images/2018/03/29/BL-beam-grey-1.th.png)](https://scrot.moe/image/91o8m)
[![BL-beam-plain-grey-1.th.png](https://cdn.scrot.moe/images/2018/03/29/BL-beam-plain-grey-1.th.png)](https://scrot.moe/image/91HP6)
I am going to issue a pull request with the actual .xcf files as well. Without the originals, making edits becomes more time-consuming and difficult than it really needs to be, imo.

I apologize for my slowness in getting to this. I have been in the middle of finals for school this week.

**Comment by johnraff** [comment]
@tknomanzr Sorry to badger you like this, when you're busy with more important things. These images look very nice - the layout is now perfect, thank you for taking the time to do this.

They are still .png files, though, and the filesizes are very big. Could you also put them through the same jpg conversion that you did previously? That should get them down to ~1MB I guess?

Also, your recent PR was aginst the 'master' branch, which is now obsolete.
There will soon (possibly today) be a renaming of all GitHub repo branches, **master** > **hydrogen** and **helium-dev** > **helium**.
**helium** will become the default branch in most repos.

**Comment by tknomanzr** [comment]
Oops. Sorry. I forgot about that. Here is the jpegs
[![BL-beam-1.th.jpg](https://cdn.scrot.moe/images/2018/03/30/BL-beam-1.th.jpg)](https://scrot.moe/image/91f30)
[![BL-beam-grey-1.th.jpg](https://cdn.scrot.moe/images/2018/03/30/BL-beam-grey-1.th.jpg)](https://scrot.moe/image/91hZA)
[![BL-beam-plain-1.th.jpg](https://cdn.scrot.moe/images/2018/03/30/BL-beam-plain-1.th.jpg)](https://scrot.moe/image/91r5L)
[![BL-beam-plain-grey-1.th.jpg](https://cdn.scrot.moe/images/2018/03/30/BL-beam-plain-grey-1.th.jpg)](https://scrot.moe/image/961Pb)

**Comment by hhhorb** [comment]
^Those look great. Thanks!

**Comment by hhhorb** [comment]
I don't know, though. This seems rather subjective to me, the percieved image.

I gimped a new master at the same res as Williams, but this has no noise and is in PNG format. The file size is larger, but not bad...

https://raw.githubusercontent.com/hhhorb/bunsen-wallpapers/master/Beam-plain_2880-x-1800.png

This image looks smoother to me in comparison at low res, the other image looks like noisy banding.

**Comment by johnraff** [comment]
^OK @hhhorb that's a png, so if you felt like redoing the four .png versions, they can co-exist in **bunsen-images** along with @tknomanzr 's .jpgs until we decide which one to use as default. Because there's no name-clash, users can choose. The default path in **bunsen-configs**, at the moment though, points to the .jpg. That would have to be changed if we switched.

To me, they all look beautiful, so you guys decide. :)

**Comment by tknomanzr** [comment]
The top left is significantly better. The bottom right still exhibits a small amount of banding in the lower right but I believe I can live with it. If we could get those 4 re-done @hhh, that would be peachy. If you need the ./svg file for the flame and text, let me know.

**Comment by hhhorb** [comment]
>The bottom right still exhibits a small amount of banding in the lower right...

Yes, banding is most noticeable in the transition to purple. Converting to jpg at 90% quality (default GIMP export setting) makes the banding way worse to my eye. Adding a small amount of noise (25px spread) works great on my small screen but makes the file-size so much larger, 3 MB as opposed to 413 kB. @tknomanzr , what's this look like on your monitor, is it enough noise or do we need more?...

![beam-noise_2880-x-1800](https://user-images.githubusercontent.com/10426086/38261640-cee090b6-3738-11e8-8cc7-ee53e0a88e63.png)

Saving that as a jpg at 90% brings the banding back, worse than in the original png. What should we do? Use the smaller, banded png files for the standard install and offer a "hi-res" wallpaper pack in bl-welcome? Or is 12 MB for the default wallpapers (PNGs with noise added) acceptable for the full-size ISOs?

**Comment by tknomanzr** [comment]
Like I said, I believe I can live with it like this for the time being. I think when the blue transitions into purple perhaps one more gradient stop was needed. I have been trying to be considerate of folks with lower-end systems in terms of the file size for the wallpaper. Truth be told, if I had designed it, I doubt I would have dropped all the way down to purple on the spectrum anyway, I would have stopped at the dark blue. However, I know from past experience, without the gradient stops as a reference, rebuilding gradients can be a huge pain, and I suspect there is another layer where the green blends down into white as well. 

However, since we have a Hi-DPI theme up for consideration, I am not opposed to releasing it as a "Hi-DPI" wallpaper and letting the community know that it is an option that may or may not fix display anomalies. The noise is a visual illusion that helps to distract the eye from the banding, pretty much. I wish I could tell you for sure that this method or that would fix it, but when banding arises in print, a lot of times the only way we could fix it was by attempting to build the gradient with more stops. Banding on newsprint is even worse than on displays, lol. 

I would like to reassure you though, that despite the difficulties we have experienced over this development cycle, this iteration is going to be a  masterpiece. And it is going to get even better with the next point release, just as Hydrogen did. Art and software design have the characteristic in common that they are highly iterative processes.

**Comment by hhhorb** [comment]
Playing with the image some more, banding is emphasized in the desaturation process, or maybe my eye just sees it more clearly in greyscale. To compensate, I ran desaturation first, then added a 30px -edit-40px noise spread. When I start adding more noise than that, the distortion started getting more distracting than the banding to me.

Anyways, here it is, the file size is nearly half of the color version...

-edit- 40px spread is the best compromise IMO...

![beam-noise-grey_2880-x-1800](https://user-images.githubusercontent.com/10426086/38266526-e853ef76-3746-11e8-9e3b-4caeb303f5c2.png)

>Like I said, I believe I can live with it like this for the time being.

OK, check if this greyscale image is acceptable to you while I add the logos back in.

**Comment by hhhorb** [comment]
Logos added...

![beam-noise-logo_2880-x-1800](https://user-images.githubusercontent.com/10426086/38264935-811fe71e-3742-11e8-8b55-5f348d3619ba.png)

-edit- 40 px noise spread for the B&W images...
-edit- oops, wrong file...

![beam-noise-grey-logo_2880-x-1800](https://user-images.githubusercontent.com/10426086/38266810-a3930128-3747-11e8-9a5c-cf7965e67652.png)

Thunar shows those 4 walls as being 10.3 MB, that's not too bad at all IMO.

**Comment by hhhorb** [comment]
@tknomanzr , something I missed earlier in this thread while I was away, here's where the original svg files are (flame and text-flame)...

https://github.com/BunsenLabs/bunsen-images-extra/tree/helium/bl-img-extra/icon-avatar

I used text-flame.svg for these 2 new logo walls, resized and positioned according to your jpegs.

**Comment by tknomanzr** [comment]
Ok. Cool. I feel like this will work and lesson learned for us all to be more careful with use of gradients in the future. However, I have really liked the entire Beam theme overall since I first ran it. I think newer versions of Gimp, since they offer higher bit-depths will help with them.

**Comment by johnraff** [comment]
(After my picky complaints about the flame being moved from the **l** to the **e**, there it is in the original! That must have been something Damo changed.)

Anyway, what should we now do for the basic **bunsen-images** package?

> is 12 MB for the default wallpapers (PNGs with noise added) acceptable for the full-size ISOs?

Or 10.3MB in fact. Remembering that these files will go in **bunsen-images** as well as in the iso, so existing users would get that 10MB next time they upgraded. Is that acceptable for the great majority of our users?

- If so, then @hhhorb 's new png's could go in, and @tknomanzr 's jpg's taken out, and the filepaths readjusted accordingly.

- OTOH if it seems a bit bulky, put the hi-res images in **bunsen-images-extra**, keep the jpg's in bunsen-images, and possibly remove the equivalent png's from there too?

Either seems reasonably sensible, but we need to decide soonish...

**Comment by hhhorb** [comment]
>If so, then @hhhorb 's new png's could go in, and @tknomanzr 's jpg's taken out, and the filepaths readjusted accordingly.

i vote for this, though I'd suggest simplifying the file names.

I think @tknomanzr 's last comment implies that he's fine with that too, but we should wait for his response.

>After my picky complaints about the flame being moved from the l to the e, there it is in the original!

It's how it appears on our website and forum headers as well.

**Comment by tknomanzr** [comment]
I have no strong opinion either way, at this point. I would have preferred to ship .png's, however because they are lossless. Jepgs will begin to artifact after being copied, moved around, etc.

**Comment by hhhorb** [comment]
>I would have preferred to ship .png's, however because they are lossless.

So, @johnraff, leave this issue open a bit for objections/suggestions but prepare to replace the walls with these 4 PNGs? Or sooner rather than later, if it makes things easier, or I can just put the commits in myself and you can merge them, just give me the word if your plate's too full. :^)

Leave tile.png in, please. I'm unsure about grey.png given the file-size and resolution, but probably better to leave it too.

-edit- Ah, tons of noise in grey.png, that's why the file size is over a meg.

**Comment by johnraff** [comment]
> I have really liked the entire Beam theme overall since I first ran it

Same here. Every time I boot up a newly installed Helium, I think how nice it looks.

grey.png is the former "Velvet Noise". It was the Crunchbang background (maybe?) and certainly the BL Hydrogen, so I think it should stay.

> After my picky complaints about the flame being moved from the l to the e, there it is in the original!
> 
> It's how it appears on our website and forum headers as well.

But in the Hydrogen wallpapers the flame hovered over the l to look like a bunsen burner: ![flame-text-1920x1200-centre.png](https://raw.githubusercontent.com/BunsenLabs/bunsen-images-extra/helium/bl-img-extra/archives/hydrogen/wallpapers/default/flame-text-1920x1200-centre.png)
I have to say, I think it looks more elegant that way.

**Comment by hhhorb** [comment]
^ I remember those walls (early damo, I think), but we'll need to recreate that flame placement. Very easily done.

What's your thought, John, an additional 4 walls with that logo or do you want that logo as the default?

**Comment by hhhorb** [comment]
Also, that logo uses Open Sans only, not bold in the first half.

**Comment by johnraff** [comment]
Personally, I'd prefer the logo with the bunsen-burner flame placement as the default, the same as in Hydrogen. EDIT: rethought: ~~I think I prefer the non-bold first half too - a bit less assertive.~~

It's getting late to do a forum question, but @tknomanzr what do you think?

Whichever way we go, I don't think subtle choices of logo style justify multiple versions of wallpapers at several megabytes each.

**Comment by tknomanzr** [comment]
I like it over the l, to be honest. The subtle reference to the Bunsen burner is nice. It wasn't too difficult to move the flame to the right on the version I did as the paths are all still there in the .svg.  However, I think the slight difference between @capn-damo's font and the one I created would most likely be the difference in the first part being bolded. Of course, OpenSans has a number of weights, so it might have even been a semi-bold. There was a definite slight difference in the fonts that I noticed. Let me know if you need me to work on that.

**Comment by johnraff** [comment]
Actually, about the bold first-half font, I see that our current helium-dev wallpaper is that way, and it looks pretty nice too. I'd be OK either way on that.

@hhhorb ?

**Comment by hhhorb** [comment]
Fine either way by me, it's splitting hairs.

Commit and close this issue! :^D

**Comment by hhhorb** [comment]
@William, it was light and semi-bold, IIRC. Or bold and semi-light. :P

**Comment by tknomanzr** [comment]
OK. I'll work it up and get you a commit on it.

**Comment by tknomanzr** [comment]
I created a pull request with the text-flame-helium.svg in it.

**Comment by johnraff** [comment]
@tknomanzr thanks for the new logo. I wonder, though, if the root directory of bunsen-images is the best place for it. (Please see my comment on the PR.)

In fact, did you intend this for users or developers to use?
Or, maybe @hhhorb can use it in a wallpaper set that we can ship in the Helium release?

**Comment by hhhorb** [comment]
The other logo is kept in a fairly obscure location, I don't think we need to repeat that. I'd say it belongs with whatever images-extra package we end up with.

Very easy to make new walls with this logo. Not tonight, though, :)

**Comment by hhhorb** [comment]
HoaS pointed out that ututo's crystal wall solves the banding issue...

https://www.dropbox.com/sh/3b9u9hkem4f1ayu/AADqkCm7hUvmyG-SIVv1rZAja/beam_crystal-2560x1080.png?dl=0
https://www.dropbox.com/sh/3b9u9hkem4f1ayu/AADBhIjHLCGD1W1yn2yZ1rzma/beam_crystal-1920x1200.png?dl=0

We could use one of these as the default (with logo), or I could ask him to do one in 2880x1800 or some other resolution. I love it, it looks like an image of the Loch Ness Monster's skull and vertebrae, or maybe a chestburster face-up, ready to burst some chest, bitches. Wadda' y'all think?

**Comment by johnraff** [comment]
> it looks like an image of the Loch Ness Monster's skull and vertebrae, or maybe a chestburster face-up, ready to burst some chest, bitches

OK. It's very impressive, but not exactly *restful* IMHO. I would find it rather distracting to use on a daily basis - getting a bit far away from CrunchBang's "pleasantly boring". 

I'd rather have a bit of banding - which I can't see anyway - the beam wallpaper is really beautiful and one I could see living with. The "crystal" variant OTOH I would change immediately.

But that's just one opinion.

**Comment by tknomanzr** [comment]
I have been using the stock Helium look all the way down the line for a couple of days now, and I have to say that I am very happy with it. The last batch of wallpapers you produced did it for me. I have a bit of banding in the lower right but it is not bad enough to be distracting. I would definitely put his work in bunsen-images-extra, though.

**Comment by hhhorb** [comment]
Ok, those comments are fair, and there's no need to change the wall at this late date and with the work put in already.

I got you with chestburster, John, didn't I. :D
Extras or forum post it is.

**Comment by johnraff** [comment]
^Yup.

@hhhorb maybe you could put @tknomanzr 's new logo into a green and grey wallpaper from your last set? Then we've got four to put into **bunsen-images**. At that point I'll remove the temporary .jpgs, and update the config paths in **bunsen-configs**. There probably aren't all that many users with wallpapers set to jpg, and it's not that hard to reset to a png.

Ututo's work is outstanding, and for sure let's make it available to our users. Anyway **bunsen-images-extra** is perhaps too big already, and could be broken into two? Discussion after the release...

**Comment by hhhorb** [comment]
Here they are, to avoid confusion I have them all in a subfolder of my wallpaper repo...

https://github.com/hhhorb/bunsen-wallpapers/tree/master/Beam-final

I noticed the logo color, which William faithfully recreated from my original walls, was different than the conky color, so I used the conky color instead since it produced a better "glow".

Suggesting this issue be resolved, we should open a new one for the restructuring of all Bunsen images.

**Comment by hhhorb** [comment]
Preview of the new default wallpaper...

![beam-logo_4-11](https://user-images.githubusercontent.com/10426086/38637904-84bc5f52-3d9a-11e8-9e57-660056a353d2.png)

**Comment by tknomanzr** [comment]
That looks a bit better. A little less pale. For sure, a discussion on images will be a good thing. I still highly recommend we have a repository for original files such as .xcf of .svg files so that we can avoid scenarios such as this in the future.

**Comment by johnraff** [comment]
Beautiful, @hhhorb thanks! At ~3MB each they're a bit on the big side, but let's accept that as a compromise most users should be able to live with. I'll put them in **bunsen-images**, ~~remove the jpgs~~ no, in fact, since they're not so big, let's leave the jpgs in too for a while, at least until after the official release is out. But I'll also rewrite the paths in **bunsen-configs** and **bunsen-utilities** to point to the pngs.


> I still highly recommend we have a repository for original files such as .xcf of .svg files

Let's put them in a git repository **bunsen-images-dev** and have it available as a package for people who want to help us out with artwork.

**Comment by hhhorb** [comment]
Agreed, and thanks!

**Comment by hhhorb** [comment]
Also...

https://github.com/BunsenLabs/bunsen-images-extra/issues/3#

https://github.com/hhhorb/bunsen-wallpapers/tree/master/bunsen-helium-images-extra-dev

**Comment by johnraff** [comment]
^A comment also left over there.

**Comment by tknomanzr** [comment]
I think we can close this issue now.
